services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Set your SQL Server sa password here
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data  # Optional: Persist data outside the container
    platform: linux/amd64
    user: root

volumes:
  sql_data: